// ─── Learning Sheet Types ─────────────────────────────────────────────────────

/** Praxis-branded difficulty levels */
export type Difficulty = string;

/** Content categories for prompt routing */
export type SheetCategory =
  | 'dsa'
  | 'ml'
  | 'llm'
  | 'system-design'
  | 'os'
  | 'dbms'
  | 'networks'
  | 'devops'
  | 'languages';

/** Supported programming languages for code generation */
export type CodeLanguage = 'python' | 'java' | 'cpp' | 'javascript' | 'go' | 'rust';

/** Difficulty display metadata */
export const DIFFICULTY_META: Record<string, { label: string; color: string; bg: string; border: string }> = {
  fundamentals: { label: 'Fundamentals', color: '#4ade80', bg: 'rgba(34,197,94,0.1)',  border: 'rgba(34,197,94,0.25)' },
  interview:    { label: 'Interview',    color: '#fbbf24', bg: 'rgba(251,191,36,0.1)', border: 'rgba(251,191,36,0.25)' },
  expert:       { label: 'Expert',       color: '#f87171', bg: 'rgba(248,113,113,0.1)', border: 'rgba(248,113,113,0.25)' },
  beginner:     { label: 'Beginner',     color: '#4ade80', bg: 'rgba(34,197,94,0.1)',  border: 'rgba(34,197,94,0.25)' },
  intermediate: { label: 'Intermediate', color: '#60a5fa', bg: 'rgba(59,130,246,0.1)', border: 'rgba(59,130,246,0.25)' },
  advanced:     { label: 'Advanced',     color: '#fbbf24', bg: 'rgba(251,191,36,0.1)', border: 'rgba(251,191,36,0.25)' },
  cp:           { label: 'Competitive',  color: '#fca5a5', bg: 'rgba(239,68,68,0.1)',  border: 'rgba(239,68,68,0.25)' },
};

/** Retrieves metadata for display of any difficulty level name */
export function getDifficultyMeta(diff: string): { label: string; color: string; bg: string; border: string } {
  if (!diff) return { label: 'Unknown', color: '#a1a1aa', bg: 'rgba(161,161,170,0.1)', border: 'rgba(161,161,170,0.25)' };
  const normalized = diff.toLowerCase().trim();
  if (DIFFICULTY_META[normalized]) {
    return DIFFICULTY_META[normalized];
  }
  return {
    label: diff.charAt(0).toUpperCase() + diff.slice(1),
    color: '#fbbf24',
    bg: 'rgba(251,191,36,0.1)',
    border: 'rgba(251,191,36,0.25)',
  };
}

// ─── Data Structures ──────────────────────────────────────────────────────────

/** A practice problem recommendation */
export interface PracticeProblem {
  name: string;
  difficulty: string;
  url?: string;
  hint?: string;
}

export interface VisualMemoryHook {
  analogyName: string;
  analogyDescription: string;
}

export interface PatternRecognition {
  decisionPath: string[];
  keywords: string[];
  explanation: string;
}

// ─── Visualization schema types ───────────────────────────────────────────────

/** A step entry from the legacy step-based flowchart schema. */
export interface VisualizationStep {
  step:        number;
  action:      string;
  explanation: string;
  left?:       number;
  right?:      number;
  pointers?:   Array<{ name: string; index: number }>;
  row?:        number;
  col?:        number;
  val?:        string;
  state?:      string[];
}

/** A node in the graph flowchart schema. */
export interface VisualizationNode {
  id:           string;
  label:        string;
  explanation?: string;
}

/** An edge in the graph flowchart schema. */
export interface VisualizationEdge {
  from: string;
  to:   string;
}

/**
 * A "new-style" graph-based interactive visualization.
 * Produced by Gemini when generating flowchart/graph/tree diagrams
 * with explicit node/edge structure.
 */
export interface GraphVisualization {
  type:    string;
  nodes:   VisualizationNode[];
  edges:   VisualizationEdge[];
  steps?:  never;
  // Optional grid/array metadata (unused for graph type)
  array?:  string[];
  rows?:   string[];
  cols?:   string[];
}

/**
 * A "legacy-style" step-based interactive visualization.
 * Used by older stored learning sheets and pointer/grid/memory players.
 */
export interface StepVisualization {
  type:   string;
  steps:  VisualizationStep[];
  nodes?: never;
  edges?: never;
  // Optional grid/array metadata
  array?: string[];
  rows?:  string[];
  cols?:  string[];
  structure?: string;
}

/**
 * Union of both supported interactive visualization schemas.
 * The renderer accepts either form.
 */
export type InteractiveVisualization = GraphVisualization | StepVisualization;

export interface StateTimeline {
  headers: string[];
  rows: string[][];
}

export interface FundamentalsExtras {
  concept: string;
  whyItWorks: string;
}

export interface InterviewExtras {
  strategy: string;
  template: string;
  variants: string[];
  similarPatterns: Array<{ name: string; difference: string }>;
}

export interface ExpertExtras {
  invariants: string[];
  edgeCases: string[];
  alternatives: Array<{ name: string; complexity: string; prosCons: string }>;
  followUps: Array<{ question: string; answer: string }>;
  productionApplications: Array<{ system: string; useCase: string }>;
}

/**
 * Unified cheat-sheet content generated by Gemini.
 * Every field has a Zod-validated default so partial AI output is safe.
 */
export interface LearningSheetData {
  schemaVersion: number; // version 2
  title: string;
  coreIdea: string;
  analogy: VisualMemoryHook;
  recognition: PatternRecognition;
  visualization: InteractiveVisualization;
  timeline: StateTimeline;
  complexity: { time: string; timeExplanation: string; space: string; spaceExplanation: string };
  pitfalls: string[];
  practiceRoadmap: PracticeProblem[];
  
  // Difficulty levels additions (progressive)
  fundamentals?: FundamentalsExtras;
  interview?: InterviewExtras;
  expert?: ExpertExtras;

  // ── Backward Compatibility / Fallback properties ──
  recognitionClues?: string[];
  excalidrawScene?: string | Record<string, any>;
  mistakes?: string[];
  practiceProblems?: PracticeProblem[];
  personalizedMistakes?: string[];
  personalizedRecommendations?: string[];
}

/** Full API response shape from /api/learning-sheet/generate */
export interface LearningSheetResponse {
  id: string;
  topic: string;
  slug: string;
  category: SheetCategory;
  difficulty: Difficulty;
  language: string;
  version: number;
  data: LearningSheetData;
  cached: boolean;
  bookmarked: boolean;
  createdAt: string;
}

