// ─── Learning Sheet Types ─────────────────────────────────────────────────────

/** Praxis-branded difficulty levels */
export type Difficulty = 'fundamentals' | 'interview' | 'expert';

/** Content categories for prompt routing */
export type SheetCategory =
  | 'dsa'
  | 'ml'
  | 'llm'
  | 'system-design'
  | 'os'
  | 'dbms'
  | 'networks'
  | 'devops'
  | 'languages';

/** Supported programming languages for code generation */
export type CodeLanguage = 'python' | 'java' | 'cpp' | 'javascript' | 'go' | 'rust';

/** Difficulty display metadata */
export const DIFFICULTY_META: Record<Difficulty, { label: string; color: string; bg: string; border: string }> = {
  fundamentals: { label: 'Fundamentals', color: '#4ade80', bg: 'rgba(34,197,94,0.1)',  border: 'rgba(34,197,94,0.25)' },
  interview:    { label: 'Interview',    color: '#fbbf24', bg: 'rgba(251,191,36,0.1)', border: 'rgba(251,191,36,0.25)' },
  expert:       { label: 'Expert',       color: '#f87171', bg: 'rgba(248,113,113,0.1)', border: 'rgba(248,113,113,0.25)' },
};

// ─── Data Structures ──────────────────────────────────────────────────────────

/** A practice problem recommendation */
export interface PracticeProblem {
  name: string;
  difficulty: string;
  url?: string;
  hint?: string;
}

/**
 * Compact cheat-sheet content generated by Gemini.
 * ~200–250 words. No code, no diagrams, no references.
 * Every field has a Zod-validated default so partial AI output is safe.
 */
export interface LearningSheetData {
  title: string;
  /** Core idea summary — max 2 concise lines */
  coreIdea: string;
  /** Pattern recognition clues — max 5 bullets */
  recognitionClues: string[];
  /** Compact Mermaid diagram code */
  mermaidDiagram?: string;
  /** Time + space complexity with brief explanation */
  complexity: { time: string; space: string };
  /** Common mistakes to avoid — max 5 bullets */
  mistakes: string[];
  /** Related LeetCode problems — max 5 */
  practiceProblems: PracticeProblem[];
  // ── Personalization (populated when user has weakness data) ──
  personalizedMistakes?: string[];
  personalizedRecommendations?: string[];
}

/** Full API response shape from /api/learning-sheet/generate */
export interface LearningSheetResponse {
  id: string;
  topic: string;
  slug: string;
  category: SheetCategory;
  difficulty: Difficulty;
  language: string;
  version: number;
  data: LearningSheetData;
  cached: boolean;
  bookmarked: boolean;
  createdAt: string;
}
